using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Data;

namespace ARK_Server_Manager.Lib
{
    public static class GameData
    {
        private static readonly DinoSpawn[] dinoSpawns = new DinoSpawn[] 
            {
                new DinoSpawn { ClassName="Ankylo_Character_BP_C", DinoNameTag = "Anky",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Ant_Character_BP_C", DinoNameTag = "Ant",        SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Argentavis_Character_BP_C", DinoNameTag = "Argent",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Bat_Character_BP_C", DinoNameTag = "Bat",        SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Sauropod_Character_BP_C", DinoNameTag = "Bronto",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Carno_Character_BP_C", DinoNameTag = "Carno",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Coel_Character_BP_C", DinoNameTag = "Coel",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Dilo_Character_BP_C", DinoNameTag = "Dilo",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Dimorph_Character_BP_C", DinoNameTag = "Dimorph",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Dodo_Character_BP_C", DinoNameTag = "Dodo",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Dolphin_Character_BP_C", DinoNameTag = "Dolphin",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Dragonfly_Character_BP_C", DinoNameTag = "Dragonfly",  SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="MegaCarno_Character_BP_C", DinoNameTag = "Elite Carno",  SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="MegaRaptor_Character_BP_C", DinoNameTag = "Elite Raptor",  SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="MegaRex_Character_BP_C", DinoNameTag = "Elite Rex",  SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Mammoth_Character_BP_C", DinoNameTag = "Mammoth",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Megalodon_Character_BP_C", DinoNameTag = "Mega",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Para_Character_BP_C", DinoNameTag = "Para",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Phiomia_Character_BP_C", DinoNameTag = "Phiomia",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Piranha_Character_BP_C", DinoNameTag = "Piranha",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Plesiosaur_Character_BP_C", DinoNameTag = "Plesiosaur", SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Ptero_Character_BP_C", DinoNameTag = "Ptera",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Raptor_Character_BP_C", DinoNameTag = "Raptor",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Rex_Character_BP_C", DinoNameTag = "Rex",        SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Saber_Character_BP_C", DinoNameTag = "Sabertooth", SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Sarco_Character_BP_C", DinoNameTag = "Sarco",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Scorpion_Character_BP_C", DinoNameTag = "Scorpion",   SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Stego_Character_BP_C", DinoNameTag = "Stego",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Spino_Character_BP_C", DinoNameTag = "Spino",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="SpiderS_Character_BP_C", DinoNameTag = "Spider",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="BoaFrill_Character_BP_C", DinoNameTag = "Titanboa",   SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Trike_Character_BP_C", DinoNameTag = "Trike",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Trilobite_Character_C", DinoNameTag = "Trilobite",  SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="Turtle_Character_BP_C", DinoNameTag = "Turtle",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { ClassName="SpiderL_Character_BP_C", DinoNameTag = "Uberspider", SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
            };

        public static string NameTagForClass(string entry) => (entry == "FlyingAnt_Character_BP_C" ? dinoSpawns.First(d => d.ClassName == "Ant_Character_BP_C") : dinoSpawns.First(d => d.ClassName == entry)).DinoNameTag;

        public static string FriendlyNameForClass(string entry) => entry == "FlyingAnt_Character_BP_C" ? "Flying Ant" : dinoSpawns.First(d => d.ClassName == entry).DinoNameTag;

        public static IEnumerable<DinoSpawn> GetDinoSpawns() => dinoSpawns.Select(d => d.Duplicate<DinoSpawn>());

        private static readonly ClassMultiplier[] standardDinoMultipliers = new ClassMultiplier[]
        {
            new ClassMultiplier { ClassName="Ankylo_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Ant_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="FlyingAnt_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Argentavis_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Bat_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="BoaFrill_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Carno_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Coel_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dilo_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dimorph_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dodo_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dolphin_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dragonfly_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Mammoth_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Megalodon_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="MegaRex_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="MegaCarno_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="MegaRaptor_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Para_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Phiomia_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Piranha_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Plesiosaur_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Ptero_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Raptor_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Rex_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Saber_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Sarco_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Sauropod_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Scorpion_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="SpiderL_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="SpiderS_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Spino_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Stego_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Trike_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Trilobite_Character_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Turtle_Character_BP_C", Multiplier = 1.0f }
        };

        public static IEnumerable<ClassMultiplier> GetStandardDinoMultipliers() => standardDinoMultipliers.Select(d => d.Duplicate<ClassMultiplier>());

        public static IEnumerable<string> GetDinoClasses() => standardDinoMultipliers.Select(d => d.ClassName);

        public static IEnumerable<NPCReplacement> GetNPCReplacements() => standardDinoMultipliers.Select(d => new NPCReplacement() { FromClassName = d.ClassName, ToClassName = d.ClassName });

        private static readonly ClassMultiplier[] standardResourceMultipliers = new ClassMultiplier[]
        {
            new ClassMultiplier { ClassName="PrimalItemResource_ApexDrop_Argentavis_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ApexDrop_Megalodon_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ApexDrop_Rex_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ApexDrop_Sauro_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Charcoal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Chitin_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ChitinOrKeratin_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ChitinPaste_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Craftable_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Crystal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Electronics_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Fibers_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Flint_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Gasoline_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Gunpowder_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Hide_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Keratin_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Metal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_MetalIngot_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Obsidian_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Oil_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Polymer_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_RareFlower_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_RareMushroom_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Silicon_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Sparkpowder_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Stone_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Temp_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Thatch_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Wood_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_RawMeat_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_RawPrimeMeat_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Amarberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Azulberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Mejoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Narcoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Stimberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Tintoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Veggie_Citronal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Veggie_Longrass_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Veggie_Rockarrot_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Veggie_Savoroot_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Amarberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Azulberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Mejoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Narcoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Stimberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Tintoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Citronal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Longrass_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Rockarrot_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Savoroot_C", Multiplier=1.0f }
        };

        public static IEnumerable<ClassMultiplier> GetStandardResourceMultipliers() => standardResourceMultipliers.Select(d => d.Duplicate<ClassMultiplier>());
       
        private static readonly Level[] levelProgression = new Level[]
            {             
                new Level {XPRequired=5	    , EngramPoints=8  },
                new Level {XPRequired=20	, EngramPoints=8  },
                new Level {XPRequired=40	, EngramPoints=8  },
                new Level {XPRequired=70	, EngramPoints=8  },
                new Level {XPRequired=120	, EngramPoints=8  },
                new Level {XPRequired=190	, EngramPoints=8  },
                new Level {XPRequired=270	, EngramPoints=8  },
                new Level {XPRequired=360	, EngramPoints=8  },
                new Level {XPRequired=450	, EngramPoints=12 },
                new Level {XPRequired=550	, EngramPoints=12 },
                new Level {XPRequired=660	, EngramPoints=12 },
                new Level {XPRequired=780	, EngramPoints=12 },
                new Level {XPRequired=910	, EngramPoints=12 },
                new Level {XPRequired=1050	, EngramPoints=12 },
                new Level {XPRequired=1200	, EngramPoints=12 },
                new Level {XPRequired=1360	, EngramPoints=12 },
                new Level {XPRequired=1530	, EngramPoints=12 },
                new Level {XPRequired=1710	, EngramPoints=12 },
                new Level {XPRequired=1900	, EngramPoints=16 },
                new Level {XPRequired=2100	, EngramPoints=16 },
                new Level {XPRequired=2310	, EngramPoints=16 },
                new Level {XPRequired=2530	, EngramPoints=16 },
                new Level {XPRequired=2760	, EngramPoints=16 },
                new Level {XPRequired=3000	, EngramPoints=16 },
                new Level {XPRequired=3250	, EngramPoints=16 },
                new Level {XPRequired=3510	, EngramPoints=16 },
                new Level {XPRequired=3780	, EngramPoints=16 },
                new Level {XPRequired=4060	, EngramPoints=16 },
                new Level {XPRequired=4350	, EngramPoints=20 },
                new Level {XPRequired=4650	, EngramPoints=20 },
                new Level {XPRequired=4960	, EngramPoints=20 },
                new Level {XPRequired=5280	, EngramPoints=20 },
                new Level {XPRequired=5610	, EngramPoints=20 },
                new Level {XPRequired=5950	, EngramPoints=20 },
                new Level {XPRequired=6300	, EngramPoints=20 },
                new Level {XPRequired=6660	, EngramPoints=20 },
                new Level {XPRequired=7030	, EngramPoints=20 },
                new Level {XPRequired=7410	, EngramPoints=20 },
                new Level {XPRequired=7800	, EngramPoints=24 },
                new Level {XPRequired=8200	, EngramPoints=24 },
                new Level {XPRequired=8610	, EngramPoints=24 },
                new Level {XPRequired=9030	, EngramPoints=24 },
                new Level {XPRequired=9460	, EngramPoints=24 },
                new Level {XPRequired=9900	, EngramPoints=24 },
                new Level {XPRequired=10350	, EngramPoints=24 },
                new Level {XPRequired=10810	, EngramPoints=24 },
                new Level {XPRequired=11280	, EngramPoints=24 },
                new Level {XPRequired=11760	, EngramPoints=24 },
                new Level {XPRequired=12250	, EngramPoints=28 },
                new Level {XPRequired=12750	, EngramPoints=28 },
                new Level {XPRequired=13260	, EngramPoints=28 },
                new Level {XPRequired=13780	, EngramPoints=28 },
                new Level {XPRequired=14310	, EngramPoints=28 },
                new Level {XPRequired=14850	, EngramPoints=28 },
                new Level {XPRequired=15400	, EngramPoints=28 },
                new Level {XPRequired=15960	, EngramPoints=28 },
                new Level {XPRequired=16530	, EngramPoints=28 },
                new Level {XPRequired=17110	, EngramPoints=28 },
                new Level {XPRequired=17700	, EngramPoints=28 },
                new Level {XPRequired=18850	, EngramPoints=28 },
                new Level {XPRequired=21078	, EngramPoints=28 },
                new Level {XPRequired=22448	, EngramPoints=28 },
                new Level {XPRequired=23908	, EngramPoints=28 },
                new Level {XPRequired=25462	, EngramPoints=28 },
                new Level {XPRequired=27498	, EngramPoints=28 },
                new Level {XPRequired=30248	, EngramPoints=28 },
                new Level {XPRequired=32043	, EngramPoints=28 },
                new Level {XPRequired=34148	, EngramPoints=28 },
                new Level {XPRequired=36254	, EngramPoints=28 },
                new Level {XPRequired=38359	, EngramPoints=28 },
                new Level {XPRequired=40465	, EngramPoints=28 },
                new Level {XPRequired=42571	, EngramPoints=28 },
                new Level {XPRequired=44676	, EngramPoints=28 },
                new Level {XPRequired=46782	, EngramPoints=28 },
                new Level {XPRequired=48887	, EngramPoints=28 },
                new Level {XPRequired=50993	, EngramPoints=28 },
                new Level {XPRequired=53099	, EngramPoints=28 },
                new Level {XPRequired=55204	, EngramPoints=28 },
                new Level {XPRequired=57310	, EngramPoints=31 },
                new Level {XPRequired=59415	, EngramPoints=31 },
                new Level {XPRequired=61521	, EngramPoints=31 },
                new Level {XPRequired=63627	, EngramPoints=31 },
                new Level {XPRequired=65732	, EngramPoints=31 },
                new Level {XPRequired=67838	, EngramPoints=31 },
                new Level {XPRequired=69943	, EngramPoints=31 },
                new Level {XPRequired=72049	, EngramPoints=31 },
                new Level {XPRequired=74155	, EngramPoints=31 },
                new Level {XPRequired=76260	, EngramPoints=31 },
                new Level {XPRequired=78366	, EngramPoints=33 },
                new Level {XPRequired=80471	, EngramPoints=33 },
                new Level {XPRequired=82577	, EngramPoints=33 },
                new Level {XPRequired=84683	, EngramPoints=33 },
                new Level {XPRequired=86788	, EngramPoints=33 },
                new Level {XPRequired=88894	, EngramPoints=33 },
                new Level {XPRequired=90999	, EngramPoints=33 },
                new Level {XPRequired=93105	, EngramPoints=33 },
                new Level {XPRequired=95211	, EngramPoints=33 },
                new Level {XPRequired=97316	, EngramPoints=33 },
                new Level {XPRequired=99422	, EngramPoints=33 },
            };

        public static IEnumerable<EngramEntry> GetStandardEngramOverrides() => engrams.Select(d => d.Duplicate<EngramEntry>());

        public static readonly EngramEntry[] engrams = new[]
        {
            new EngramEntry { EngramClassName="EngramEntry_AdvancedBullet_C",           EngramLevelRequirement=50, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_AdvancedRifleBullet_C",      EngramLevelRequirement=55, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_AirConditioner_C",           EngramLevelRequirement=55, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_AlarmTrap_C",                EngramLevelRequirement=20, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_AnvilBench_C",               EngramLevelRequirement=25, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ArrowStone_C",               EngramLevelRequirement=15, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ArrowTranq_C",               EngramLevelRequirement=20, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_BearTrap_C",                 EngramLevelRequirement=25, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_BearTrap_Large_C",           EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ArrowTranq_C",               EngramLevelRequirement=20, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_BloodExtractor_C",           EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Bookshelf_C",                EngramLevelRequirement=20, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Bow_C",                      EngramLevelRequirement=15, EngramPointsCost=11, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_C4Ammo_C",                   EngramLevelRequirement=55, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Campfire_C",                 EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Canteen_C",                  EngramLevelRequirement=50, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinBoots_C",              EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinGloves_C",             EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinHelmet_C",             EngramLevelRequirement=30, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinPants_C",              EngramLevelRequirement=30, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinPaste_C",              EngramLevelRequirement=10, EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinShirt_C",              EngramLevelRequirement=30, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothBoots_C",               EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothGloves_C",              EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothHelmet_C",              EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothPants_C",               EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothShirt_C",               EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Compass_C",                  EngramLevelRequirement=10, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CompostBin_C",               EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CompoundArrow_C",            EngramLevelRequirement=70, EngramPointsCost=35, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CompoundBow_C",              EngramLevelRequirement=70, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CookingPot_C",               EngramLevelRequirement=10, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CropPlot_Large_C",           EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CropPlot_Medium_C",          EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CropPlot_Small_C",           EngramLevelRequirement=10, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Crossbow_C",                 EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Electronics_C",              EngramLevelRequirement=40, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Fabricator_C",               EngramLevelRequirement=40, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_FeedingTrough_C",            EngramLevelRequirement=15, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Flag_C",                     EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_FlagSingle_C",               EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_FlareLauncher_C",            EngramLevelRequirement=10, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Flashlight_C",               EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Forge_C",                    EngramLevelRequirement=20, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_GPS_C",                      EngramLevelRequirement=45, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Grenade_C",                  EngramLevelRequirement=30, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Grill_C",                    EngramLevelRequirement=45, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Gunpowder_C",                EngramLevelRequirement=10, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideBoots_C",                EngramLevelRequirement=20, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideGloves_C",               EngramLevelRequirement=20, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideHelmet_C",               EngramLevelRequirement=20, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HidePants_C",                EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideShirt_C",                EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideSleepingBag_C",          EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HoloScope_C",                EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_IceBox_C",                   EngramLevelRequirement=55, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Keypad_C",                   EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Lamppost_C",                 EngramLevelRequirement=50, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_LamppostOmni_C",             EngramLevelRequirement=50, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Laser_C",                    EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MachinedPistol_C",           EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MachinedRifle_C",            EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MachinedShotgun_C",          EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalBoots_C",               EngramLevelRequirement=50, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalCatwalk_C",             EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalCeiling_C",             EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalCeilingWithTrapdoor_C", EngramLevelRequirement=40, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalDoor_C",                EngramLevelRequirement=35, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalFenceFoundation_C",     EngramLevelRequirement=40, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalFloor_C",               EngramLevelRequirement=30, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGate_C",                EngramLevelRequirement=40, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGateway_C",             EngramLevelRequirement=40, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGateway_Large_C",       EngramLevelRequirement=55, EngramPointsCost=28, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGate_Large_C",          EngramLevelRequirement=55, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGloves_C",              EngramLevelRequirement=50, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalHatchet_C",             EngramLevelRequirement=25, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalHelmet_C",              EngramLevelRequirement=50, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalLadder_C",              EngramLevelRequirement=45, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPants_C",               EngramLevelRequirement=45, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPick_C",                EngramLevelRequirement=25, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPillar_C",              EngramLevelRequirement=35, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeIncline_C",         EngramLevelRequirement=45, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeIntake_C",          EngramLevelRequirement=40, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeIntersection_C",    EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeStraight_C",        EngramLevelRequirement=40, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeTap_C",             EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeVertical_C",        EngramLevelRequirement=45, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalRamp_C",                EngramLevelRequirement=35, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalShirt_C",               EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSickle_C",              EngramLevelRequirement=30, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSign_C",                EngramLevelRequirement=25, EngramPointsCost=10, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSign_Large_C",          EngramLevelRequirement=50, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSign_Wall_C",           EngramLevelRequirement=30, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSpikeWall_C",           EngramLevelRequirement=25, EngramPointsCost=11, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalTrapdoor_C",            EngramLevelRequirement=40, EngramPointsCost=14, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalWall_C",                EngramLevelRequirement=30, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalWallWithDoor_C",        EngramLevelRequirement=30, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalWallWithWindow_C",      EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalWindow_C",              EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MinersHelmet_C",             EngramLevelRequirement=65, EngramPointsCost=35, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MiracleGro_C",               EngramLevelRequirement=35, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MortarAndPestle_C",          EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Narcotic_C",                 EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_NotePaper_C",                EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Paintbrush_C",               EngramLevelRequirement=5,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Parachute_C",                EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Pike_C",                     EngramLevelRequirement=25, EngramPointsCost=10, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Pistol_C",                   EngramLevelRequirement=30, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PoisonTrap_C",               EngramLevelRequirement=25, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Polymer_C",                  EngramLevelRequirement=40, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerCableIncline_C",        EngramLevelRequirement=55, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerCableIntersection_C",   EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerCableStraight_C",       EngramLevelRequirement=50, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerCableVertical_C",       EngramLevelRequirement=55, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerGenerator_C",           EngramLevelRequirement=50, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerOutlet_C",              EngramLevelRequirement=50, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PreservingBin_C",            EngramLevelRequirement=20, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_RocketAmmo_C",               EngramLevelRequirement=60, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_RocketLauncher_C",           EngramLevelRequirement=60, EngramPointsCost=32, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Ankylo_C",            EngramLevelRequirement=40, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Argentavis_C",        EngramLevelRequirement=55, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Carno_C",             EngramLevelRequirement=50, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Dolphin_C",           EngramLevelRequirement=10, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Mammoth_C",           EngramLevelRequirement=40, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Megalodon_C",         EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Para_C",              EngramLevelRequirement=10, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Phiomia_C",           EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Plesia_C",            EngramLevelRequirement=60, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Ptero_C",             EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Raptor_C",            EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Rex_C",               EngramLevelRequirement=60, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Saber_C",             EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Sarco_C",             EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Sauro_C",             EngramLevelRequirement=55, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Scorpion_C",          EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Spino_C",             EngramLevelRequirement=60, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Stego_C",             EngramLevelRequirement=30, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Trike_C",             EngramLevelRequirement=20, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Turtle_C",            EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Scope_C",                    EngramLevelRequirement=30, EngramPointsCost=13, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Silencer_C",                 EngramLevelRequirement=40, EngramPointsCost=13, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleBed_C",                EngramLevelRequirement=5,  EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleBullet_C",             EngramLevelRequirement=30, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleRifle_C",              EngramLevelRequirement=35, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleRifleBullet_C",        EngramLevelRequirement=35, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleShotgun_C",            EngramLevelRequirement=35, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleShotgunBullet_C",      EngramLevelRequirement=35, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Slingshot_C",                EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Sparkpowder_C",              EngramLevelRequirement=5,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Spear_C",                    EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Spyglass_C",                 EngramLevelRequirement=10, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StandingTorch_C",            EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Stimulant_C",                EngramLevelRequirement=10, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneCeiling_C",             EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneCeilingWithTrapdoor_C", EngramLevelRequirement=25, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneDoor_C",                EngramLevelRequirement=20, EngramPointsCost=4,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneFenceFoundation_C",     EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneFloor_C",               EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneGate_C",                EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneGateLarge_C",           EngramLevelRequirement=30, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneGateway_C",             EngramLevelRequirement=20, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneGateway_Large_C",       EngramLevelRequirement=30, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneHatchet_C",             EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePillar_C",              EngramLevelRequirement=25, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeInclined_C",        EngramLevelRequirement=15, EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeIntake_C",          EngramLevelRequirement=10, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeIntersection_C",    EngramLevelRequirement=15, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeStraight_C",        EngramLevelRequirement=10, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeTap_C",             EngramLevelRequirement=10, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeVertical_C",        EngramLevelRequirement=15, EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneTrapdoor_C",            EngramLevelRequirement=30, EngramPointsCost=10, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneWall_C",                EngramLevelRequirement=15, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneWallWithDoor_C",        EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneWallWithWindow_C",      EngramLevelRequirement=25, EngramPointsCost=11, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneWindow_C",              EngramLevelRequirement=30, EngramPointsCost=10, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StorageBox_Huge_C",          EngramLevelRequirement=65, EngramPointsCost=30, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StorageBox_Large_C",         EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StorageBox_Small_C",         EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchCeiling_C",            EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchDoor_C",               EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchFloor_C",              EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchWall_C",               EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchWallWithDoor_C",       EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_TransGPS_C",                 EngramLevelRequirement=65, EngramPointsCost=30, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_TransGPSAmmo_C",             EngramLevelRequirement=65, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_TripwireC4_C",               EngramLevelRequirement=45, EngramPointsCost=30, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Turret_C",                   EngramLevelRequirement=60, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WaterJar_C",                 EngramLevelRequirement=30, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Waterskin_C",                EngramLevelRequirement=3,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WaterTank_C",                EngramLevelRequirement=15, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WaterTankMetal_C",           EngramLevelRequirement=45, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WeaponC4_C",                 EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodCatwalk_C",              EngramLevelRequirement=20, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodCeiling_C",              EngramLevelRequirement=10, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodCeilingWithTrapdoor_C",  EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodDoor_C",                 EngramLevelRequirement=10, EngramPointsCost=4,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodFenceFoundation_C",      EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodFloor_C",                EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodGate_C",                 EngramLevelRequirement=15, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodGateway_C",              EngramLevelRequirement=15, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodLadder_C",               EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodPillar_C",               EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodRamp_C",                 EngramLevelRequirement=15, EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodSign_C",                 EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodSign_Large_C",           EngramLevelRequirement=15, EngramPointsCost=4,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodSign_Wall_C",            EngramLevelRequirement=10, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodSpikeWall_C",            EngramLevelRequirement=10, EngramPointsCost=4,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodTrapdoor_C",             EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodWall_C",                 EngramLevelRequirement=5,  EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodWallWithDoor_C",         EngramLevelRequirement=10, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodWallWithWindow_C",       EngramLevelRequirement=20, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodWindow_C",               EngramLevelRequirement=25, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
        };

        public static IEnumerable<Level> LevelProgression => levelProgression.Select(l => l.Duplicate());
    }
}
