using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Data;

namespace ARK_Server_Manager.Lib
{
    public static class GameData
    {
        private static readonly DinoSpawn[] dinoSpawns = new DinoSpawn[] 
            {
                new DinoSpawn { DinoNameTag = "Anky",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Ant",        SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Argent",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Bat",        SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Bronto",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Carno",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Coel",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Dilo",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Dimo",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Dodo",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Dolphin",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Flyingant",  SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },                
                new DinoSpawn { DinoNameTag = "Mammoth",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Mega",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Para",       SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Phiomia",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Piranha",    SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Plesiosaur", SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Ptera",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Raptor",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Rex",        SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Sabertooth", SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Sarco",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Scorpion",   SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Stego",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Spino",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Spider",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Titanboa",   SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Trike",      SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Trilobite",  SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F },
                new DinoSpawn { DinoNameTag = "Turtle",     SpawnWeightMultiplier = 0.1F, OverrideSpawnLimitPercentage = true, SpawnLimitPercentage = 1.0F }
            };

        public static IEnumerable<DinoSpawn> GetDinoSpawns() => dinoSpawns.Select(d => d.Duplicate<DinoSpawn>());

        private static readonly ClassMultiplier[] standardDinoMultipliers = new ClassMultiplier[]
        {
            new ClassMultiplier { ClassName="Ankylo_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Ant_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="FlyingAnt_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Argent_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Bat_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="BoaFrill_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Carno_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Coel_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dilo_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dimorph_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dodo_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Dolphin_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Mammoth_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Megalodon_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Para_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Phiomia_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Piranha_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Plesiosaur_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Ptero_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Raptor_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Stego_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Rex_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Saber_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Sarco_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Sauropod_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Scorpion_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="SpiderL_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="SpiderS_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Spino_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Stego_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Trike_Character_BP_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Trilobite_Character_C", Multiplier = 1.0f },
            new ClassMultiplier { ClassName="Turtle_Character_BP_C", Multiplier = 1.0f }
        };

        public static IEnumerable<ClassMultiplier> GetStandardDinoMultipliers() => standardDinoMultipliers.Select(d => d.Duplicate<ClassMultiplier>());

        private static readonly ClassMultiplier[] standardResourceMultipliers = new ClassMultiplier[]
        {
            new ClassMultiplier { ClassName="PrimalItemResource_ApexDrop_Argentavis_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ApexDrop_Megalodon_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ApexDrop_Rex_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ApexDrop_Sauro_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Charcoal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Chitin_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ChitinOrKeratin_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_ChitinPaste_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Craftable_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Crystal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Electronics_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Fibers_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Flint_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Gasoline_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Gunpowder_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Hide_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Keratin_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Metal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_MetalIngot_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Obsidian_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Oil_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Polymer_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_RareFlower_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_RareMushroom_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Silicon_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Sparkpowder_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Stone_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Temp_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Thatch_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName="PrimalItemResource_Wood_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_RawMeat_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_RawPrimeMeat_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Amarberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Azulberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Mejoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Narcoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Stimberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Berry_Tintoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Veggie_Citronal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Veggie_Longrass_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Veggie_Rockarrot_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Veggie_Savoroot_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Amarberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Azulberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Mejoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Narcoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Stimberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Tintoberry_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Citronal_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Longrass_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Rockarrot_C", Multiplier=1.0f },
            new ClassMultiplier { ClassName = "PrimalItemConsumable_Seed_Savoroot_C", Multiplier=1.0f }
        };

        public static IEnumerable<ClassMultiplier> GetStandardResourceMultipliers() => standardResourceMultipliers.Select(d => d.Duplicate<ClassMultiplier>());
       
        private static readonly Level[] levelProgression = new Level[]
            {             
                new Level {XPRequired=5	    , EngramPoints=8  },
                new Level {XPRequired=20	, EngramPoints=8  },
                new Level {XPRequired=40	, EngramPoints=8  },
                new Level {XPRequired=70	, EngramPoints=8  },
                new Level {XPRequired=120	, EngramPoints=8  },
                new Level {XPRequired=190	, EngramPoints=8  },
                new Level {XPRequired=270	, EngramPoints=8  },
                new Level {XPRequired=360	, EngramPoints=8  },
                new Level {XPRequired=450	, EngramPoints=12 },
                new Level {XPRequired=550	, EngramPoints=12 },
                new Level {XPRequired=660	, EngramPoints=12 },
                new Level {XPRequired=780	, EngramPoints=12 },
                new Level {XPRequired=910	, EngramPoints=12 },
                new Level {XPRequired=1050	, EngramPoints=12 },
                new Level {XPRequired=1200	, EngramPoints=12 },
                new Level {XPRequired=1360	, EngramPoints=12 },
                new Level {XPRequired=1530	, EngramPoints=12 },
                new Level {XPRequired=1710	, EngramPoints=12 },
                new Level {XPRequired=1900	, EngramPoints=16 },
                new Level {XPRequired=2100	, EngramPoints=16 },
                new Level {XPRequired=2310	, EngramPoints=16 },
                new Level {XPRequired=2530	, EngramPoints=16 },
                new Level {XPRequired=2760	, EngramPoints=16 },
                new Level {XPRequired=3000	, EngramPoints=16 },
                new Level {XPRequired=3250	, EngramPoints=16 },
                new Level {XPRequired=3510	, EngramPoints=16 },
                new Level {XPRequired=3780	, EngramPoints=16 },
                new Level {XPRequired=4060	, EngramPoints=16 },
                new Level {XPRequired=4350	, EngramPoints=20 },
                new Level {XPRequired=4650	, EngramPoints=20 },
                new Level {XPRequired=4960	, EngramPoints=20 },
                new Level {XPRequired=5280	, EngramPoints=20 },
                new Level {XPRequired=5610	, EngramPoints=20 },
                new Level {XPRequired=5950	, EngramPoints=20 },
                new Level {XPRequired=6300	, EngramPoints=20 },
                new Level {XPRequired=6660	, EngramPoints=20 },
                new Level {XPRequired=7030	, EngramPoints=20 },
                new Level {XPRequired=7410	, EngramPoints=20 },
                new Level {XPRequired=7800	, EngramPoints=24 },
                new Level {XPRequired=8200	, EngramPoints=24 },
                new Level {XPRequired=8610	, EngramPoints=24 },
                new Level {XPRequired=9030	, EngramPoints=24 },
                new Level {XPRequired=9460	, EngramPoints=24 },
                new Level {XPRequired=9900	, EngramPoints=24 },
                new Level {XPRequired=10350	, EngramPoints=24 },
                new Level {XPRequired=10810	, EngramPoints=24 },
                new Level {XPRequired=11280	, EngramPoints=24 },
                new Level {XPRequired=11760	, EngramPoints=24 },
                new Level {XPRequired=12250	, EngramPoints=28 },
                new Level {XPRequired=12750	, EngramPoints=28 },
                new Level {XPRequired=13260	, EngramPoints=28 },
                new Level {XPRequired=13780	, EngramPoints=28 },
                new Level {XPRequired=14310	, EngramPoints=28 },
                new Level {XPRequired=14850	, EngramPoints=28 },
                new Level {XPRequired=15400	, EngramPoints=28 },
                new Level {XPRequired=15960	, EngramPoints=28 },
                new Level {XPRequired=16530	, EngramPoints=28 },
                new Level {XPRequired=17110	, EngramPoints=28 },
                new Level {XPRequired=17700	, EngramPoints=28 },
                new Level {XPRequired=18850	, EngramPoints=28 },
                new Level {XPRequired=21078	, EngramPoints=28 },
                new Level {XPRequired=22448	, EngramPoints=28 },
                new Level {XPRequired=23908	, EngramPoints=28 },
                new Level {XPRequired=25462	, EngramPoints=28 },
                new Level {XPRequired=27498	, EngramPoints=28 },
                new Level {XPRequired=30248	, EngramPoints=28 },
                new Level {XPRequired=32043	, EngramPoints=28 },
                new Level {XPRequired=34148	, EngramPoints=28 },
                new Level {XPRequired=36254	, EngramPoints=28 },
                new Level {XPRequired=38359	, EngramPoints=28 },
                new Level {XPRequired=40465	, EngramPoints=28 },
                new Level {XPRequired=42571	, EngramPoints=28 },
                new Level {XPRequired=44676	, EngramPoints=28 },
                new Level {XPRequired=46782	, EngramPoints=28 },
                new Level {XPRequired=48887	, EngramPoints=28 },
                new Level {XPRequired=50993	, EngramPoints=28 },
                new Level {XPRequired=53099	, EngramPoints=28 },
                new Level {XPRequired=55204	, EngramPoints=28 },
                new Level {XPRequired=57310	, EngramPoints=31 },
                new Level {XPRequired=59415	, EngramPoints=31 },
                new Level {XPRequired=61521	, EngramPoints=31 },
                new Level {XPRequired=63627	, EngramPoints=31 },
                new Level {XPRequired=65732	, EngramPoints=31 },
                new Level {XPRequired=67838	, EngramPoints=31 },
                new Level {XPRequired=69943	, EngramPoints=31 },
                new Level {XPRequired=72049	, EngramPoints=31 },
                new Level {XPRequired=74155	, EngramPoints=31 },
                new Level {XPRequired=76260	, EngramPoints=31 },
                new Level {XPRequired=78366	, EngramPoints=33 },
                new Level {XPRequired=80471	, EngramPoints=33 },
                new Level {XPRequired=82577	, EngramPoints=33 },
                new Level {XPRequired=84683	, EngramPoints=33 },
                new Level {XPRequired=86788	, EngramPoints=33 },
                new Level {XPRequired=88894	, EngramPoints=33 },
                new Level {XPRequired=90999	, EngramPoints=33 },
                new Level {XPRequired=93105	, EngramPoints=33 },
                new Level {XPRequired=95211	, EngramPoints=33 },
                new Level {XPRequired=97316	, EngramPoints=33 },
                new Level {XPRequired=99422	, EngramPoints=33 },
            };

        public static IEnumerable<EngramEntry> GetStandardEngramOverrides() => engrams.Select(d => d.Duplicate<EngramEntry>());

        public static readonly EngramEntry[] engrams = new[]
        {
            new EngramEntry { EngramClassName="EngramEntry_AdvancedBullet",           EngramLevelRequirement=50, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_AdvancedRifleBullet",      EngramLevelRequirement=55, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_AirConditioner",           EngramLevelRequirement=55, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_AlarmTrap",                EngramLevelRequirement=20, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_AnvilBench",               EngramLevelRequirement=25, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ArrowStone",               EngramLevelRequirement=15, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ArrowTranq",               EngramLevelRequirement=20, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_BloodExtractor",           EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Bookshelf",                EngramLevelRequirement=20, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Bow",                      EngramLevelRequirement=15, EngramPointsCost=11, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_C4Ammo",                   EngramLevelRequirement=55, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Campfire",                 EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Canteen",                  EngramLevelRequirement=50, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinBoots",              EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinGloves",             EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinHelmet",             EngramLevelRequirement=30, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinPants",              EngramLevelRequirement=30, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinPaste",              EngramLevelRequirement=10, EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ChitinShirt",              EngramLevelRequirement=30, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothBoots",               EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothGloves",              EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothHelmet",              EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothPants",               EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ClothShirt",               EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Compass",                  EngramLevelRequirement=10, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CompostBin",               EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CompoundArrow",            EngramLevelRequirement=70, EngramPointsCost=35, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CompoundBow",              EngramLevelRequirement=70, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CookingPot",               EngramLevelRequirement=10, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CropPlot_Large",           EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CropPlot_Medium",          EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_CropPlot_Small",           EngramLevelRequirement=10, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Crossbow",                 EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Electronics",              EngramLevelRequirement=40, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Fabricator",               EngramLevelRequirement=40, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_FeedingTrough",            EngramLevelRequirement=15, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Flag",                     EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_FlagSingle",               EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_FlareLauncher",            EngramLevelRequirement=10, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Flashlight",               EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Forge",                    EngramLevelRequirement=20, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_GPS",                      EngramLevelRequirement=45, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Grenade",                  EngramLevelRequirement=30, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Grill",                    EngramLevelRequirement=45, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Gunpowder",                EngramLevelRequirement=10, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideBoots",                EngramLevelRequirement=20, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideGloves",               EngramLevelRequirement=20, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideHelmet",               EngramLevelRequirement=20, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HidePants",                EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideShirt",                EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HideSleepingBag",          EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_HoloScope",                EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_IceBox",                   EngramLevelRequirement=55, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Keypad",                   EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Lamppost",                 EngramLevelRequirement=50, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_LamppostOmni",             EngramLevelRequirement=50, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Laser",                    EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MachinedPistol",           EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MachinedRifle",            EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MachinedShotgun",          EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalBoots",               EngramLevelRequirement=50, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalCatwalk",             EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalCeiling",             EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalCeilingWithTrapdoor", EngramLevelRequirement=40, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalDoor",                EngramLevelRequirement=35, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalFenceFoundation",     EngramLevelRequirement=40, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalFloor",               EngramLevelRequirement=30, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGate",                EngramLevelRequirement=40, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGateway",             EngramLevelRequirement=40, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGateway_Large",       EngramLevelRequirement=55, EngramPointsCost=28, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGate_Large",          EngramLevelRequirement=55, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalGloves",              EngramLevelRequirement=50, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalHatchet",             EngramLevelRequirement=25, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalHelmet",              EngramLevelRequirement=50, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalLadder",              EngramLevelRequirement=45, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPants",               EngramLevelRequirement=45, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPick",                EngramLevelRequirement=25, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPillar",              EngramLevelRequirement=35, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeIncline",         EngramLevelRequirement=45, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeIntake",          EngramLevelRequirement=40, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeIntersection",    EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeStraight",        EngramLevelRequirement=40, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeTap",             EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalPipeVertical",        EngramLevelRequirement=45, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalRamp",                EngramLevelRequirement=35, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalShirt",               EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSickle",              EngramLevelRequirement=25, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSign",                EngramLevelRequirement=25, EngramPointsCost=10, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSign_Large",          EngramLevelRequirement=50, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSign_Wall",           EngramLevelRequirement=30, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalSpikeWall",           EngramLevelRequirement=25, EngramPointsCost=11, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalTrapdoor",            EngramLevelRequirement=40, EngramPointsCost=14, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalWall",                EngramLevelRequirement=30, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalWallWithDoor",        EngramLevelRequirement=30, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalWallWithWindow",      EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MetalWindow",              EngramLevelRequirement=50, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MinersHelmet",             EngramLevelRequirement=65, EngramPointsCost=35, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_MortarAndPestle",          EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Narcotic",                 EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_NotePaper",                EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Paintbrush",               EngramLevelRequirement=5,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Parachute",                EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Pike",                     EngramLevelRequirement=25, EngramPointsCost=10, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Pistol",                   EngramLevelRequirement=30, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PoisonTrap",               EngramLevelRequirement=25, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Polymer",                  EngramLevelRequirement=40, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerCableIncline",        EngramLevelRequirement=55, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerCableIntersection",   EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerCableStraight",       EngramLevelRequirement=50, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerCableVertical",       EngramLevelRequirement=55, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerGenerator",           EngramLevelRequirement=50, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PowerOutlet",              EngramLevelRequirement=50, EngramPointsCost=16, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_PreservingBin",            EngramLevelRequirement=20, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_RocketAmmo",               EngramLevelRequirement=60, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_RocketLauncher",           EngramLevelRequirement=60, EngramPointsCost=32, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Ankylo",            EngramLevelRequirement=40, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Argentavis",        EngramLevelRequirement=55, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Carno",             EngramLevelRequirement=50, EngramPointsCost=21, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Dolphin",           EngramLevelRequirement=10, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Mammoth",           EngramLevelRequirement=40, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Megalodon",         EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Para",              EngramLevelRequirement=10, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Phiomia",           EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Plesia",            EngramLevelRequirement=60, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Ptero",             EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Raptor",            EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Rex",               EngramLevelRequirement=60, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Saber",             EngramLevelRequirement=45, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Sarco",             EngramLevelRequirement=35, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Sauro",             EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Scorpion",          EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Spino",             EngramLevelRequirement=60, EngramPointsCost=40, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Stego",             EngramLevelRequirement=30, EngramPointsCost=15, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Trike",             EngramLevelRequirement=20, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Saddle_Turtle",            EngramLevelRequirement=25, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Scope",                    EngramLevelRequirement=30, EngramPointsCost=13, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Silencer",                 EngramLevelRequirement=40, EngramPointsCost=13, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleBed",                EngramLevelRequirement=5,  EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleBullet",             EngramLevelRequirement=30, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleRifle",              EngramLevelRequirement=35, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleRifleBullet",        EngramLevelRequirement=35, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleShotgun",            EngramLevelRequirement=35, EngramPointsCost=18, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_SimpleShotgunBullet",      EngramLevelRequirement=35, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Slingshot",                EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Sparkpowder",              EngramLevelRequirement=5,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Spear",                    EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Spyglass",                 EngramLevelRequirement=10, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StandingTorch",            EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Stimulant",                EngramLevelRequirement=10, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneCeiling",             EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneCeilingWithTrapdoor", EngramLevelRequirement=25, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneDoor",                EngramLevelRequirement=20, EngramPointsCost=4,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneFenceFoundation",     EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneFloor",               EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneGate",                EngramLevelRequirement=20, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneGateway",             EngramLevelRequirement=20, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneHatchet",             EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePillar",              EngramLevelRequirement=25, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeInclined",        EngramLevelRequirement=15, EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeIntake",          EngramLevelRequirement=10, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeIntersection",    EngramLevelRequirement=15, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeStraight",        EngramLevelRequirement=10, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeTap",             EngramLevelRequirement=10, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StonePipeVertical",        EngramLevelRequirement=15, EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneTrapdoor",            EngramLevelRequirement=30, EngramPointsCost=10, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneWall",                EngramLevelRequirement=15, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneWallWithDoor",        EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneWallWithWindow",      EngramLevelRequirement=25, EngramPointsCost=11, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StoneWindow",              EngramLevelRequirement=30, EngramPointsCost=10, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StorageBox_Huge",          EngramLevelRequirement=65, EngramPointsCost=30, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StorageBox_Large",         EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_StorageBox_Small",         EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchCeiling",            EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchDoor",               EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchFloor",              EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchWall",               EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_ThatchWallWithDoor",       EngramLevelRequirement=2,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_TransGPS",                 EngramLevelRequirement=65, EngramPointsCost=30, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_TransGPSAmmo",             EngramLevelRequirement=65, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_TripwireC4",               EngramLevelRequirement=45, EngramPointsCost=30, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Turret",                   EngramLevelRequirement=60, EngramPointsCost=48, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WaterJar",                 EngramLevelRequirement=30, EngramPointsCost=12, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_Waterskin",                EngramLevelRequirement=3,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WaterTank",                EngramLevelRequirement=15, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WaterTankMetal",           EngramLevelRequirement=45, EngramPointsCost=20, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WeaponC4",                 EngramLevelRequirement=55, EngramPointsCost=24, EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodCatwalk",              EngramLevelRequirement=20, EngramPointsCost=8,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodCeiling",              EngramLevelRequirement=10, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodCeilingWithTrapdoor",  EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodDoor",                 EngramLevelRequirement=10, EngramPointsCost=4,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodFenceFoundation",      EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodFloor",                EngramLevelRequirement=5,  EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodGate",                 EngramLevelRequirement=15, EngramPointsCost=5,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodGateway",              EngramLevelRequirement=15, EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodLadder",               EngramLevelRequirement=15, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodPillar",               EngramLevelRequirement=15, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodRamp",                 EngramLevelRequirement=15, EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodSign",                 EngramLevelRequirement=3,  EngramPointsCost=3,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodSign_Large",           EngramLevelRequirement=15, EngramPointsCost=4,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodSign_Wall",            EngramLevelRequirement=10, EngramPointsCost=2,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodSpikeWall",            EngramLevelRequirement=10, EngramPointsCost=4,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodTrapdoor",             EngramLevelRequirement=20, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodWall",                 EngramLevelRequirement=5,  EngramPointsCost=7,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodWallWithDoor",         EngramLevelRequirement=10, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodWallWithWindow",       EngramLevelRequirement=20, EngramPointsCost=9,  EngramHidden=false, RemoveEngramPreReq=false },
            new EngramEntry { EngramClassName="EngramEntry_WoodWindow",               EngramLevelRequirement=25, EngramPointsCost=6,  EngramHidden=false, RemoveEngramPreReq=false },
        };

        public static IEnumerable<Level> LevelProgression => levelProgression.Select(l => l.Duplicate());
    }
}
